### ISSUE TITLE
SystemMessage Flow not working 'template' error

### ISSUE THREAD

**Issue by cirqleBio** [logspace-ai/langflow#1085]
**Describe the bug**
Initialy i did not see Human and System Messages among others in my langflow project.
I modified config file.
The prompts are now visible as potential nodes. 
I opened community example flow with system message (SystemMessageExample)
However when I want to compile the flow the error occurs. What could be the reason ?

**Browser and Version**
 - Browser chrome
 - Version Version 117.0.5938.62 (Official Build) (arm64)

**To Reproduce**
LangFlow v0.2.7
I modified config file because it missed system and human message prompts. 

```
prompts:
  ChatMessagePromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/msg_prompt_templates"
  HumanMessagePromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts"
  SystemMessagePromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts"
  ChatPromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts"
  PromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/"
```
Fork example flow (SystemMessage Example)
Run flow

**Screenshots**
<img width="1434" alt="image" src="https://github.com/logspace-ai/langflow/assets/113333745/7e7e3faf-d29c-4cdf-aa55-08cd6c60a3a3">
