### ISSUE TITLE
Password inputs aren't masked in Firefox

### ISSUE THREAD

**Issue by notpushkin** [logspace-ai/langflow#143]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/1298948/230782913-a067d4b4-be4a-4cd2-9a0c-b9f203717aeb.png">

This is because Firefox doesn't support `-webkit-text-security`, which is used in the `.password` class. You can sidestep it though by using https://github.com/noppa/text-security:

```css
// npm install --save text-security
@import "text-security/text-security.css";

@supports not (-webkit-text-security: disc) {
  .password {
    font-family: text-security-disc;
  }
}
```

Demo:
