### ISSUE TITLE
Local Server setup with Docker

### ISSUE THREAD

**Issue by cogscides** [logspace-ai/langflow#19]
Hey LangFlow Dev Team!

I have a feature request that I think would be awesome for the platform. Can you add a local server with Docker, so users can use chained prompts on local networks? It's like an OpenAI API server proxy, and would let us experiment with more complex flows for personal servers and systems.

**Comment by ogabrielluiz** [comment]
Hey @cogscides! 

I'm not sure I understand it. 

Do you mean a person uses another person's flow or just deploy with an external IP for a local network?

**Comment by cogscides** [comment]
Second one. I mean ability to deploy via docker and than use it as API.

Sharing prompt also would be very nice. It's very similar to what n8n do.

**Comment by ogabrielluiz** [comment]
We have implemented exporting and importing in the app, and also importing
an exported JSON file into a LangChain object.

We are still fleshing it out, especially the documentation, but it is
there, so you can share and import other's flows.

About the n8n approach, that is something we might consider at some point.
Now, serving it on a local network is definitely a use case we aim on
making it work.

**Comment by mikeg0** [comment]
@cogscides I got langflow working w/ Docker and nginx locally (VirtualBox Ubuntu VM hosted on win11; containers are running on Ubuntu)


It requires a code change in `langflow/backend/langflow_backend/__main__.py` (Docker cannot use loopback IP, needs to be `0.0.0.0`)
![image](https://user-images.githubusercontent.com/1077290/225725758-dd33bb65-16e6-4db2-aa1b-6ad50b8dd20f.png)

docker-compose.yml
```
version: '3'

services:
  langflow-nginx:
    image: nginx:1.19-alpine
    container_name: langflow-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80"
    depends_on:
      - langflow-backend

  langflow-backend:
    build:
      context: ./
      dockerfile: ./python.Dockerfile
    container_name: langflow-backend
    image: langflow-backend-python
    ports:
      - "5003:5003"
    entrypoint:
      - bash
    tty: true
    stdin_open: true
```


nginx.conf
```
upstream langflow-backend-server {
    server langflow-backend:5003;
}


server {
    listen 80;

    server_name langflow.dev.x.com;  # change this to your hostname

    root /langflow;

    location / {
        proxy_pass http://langflow-backend-server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```
ensure langflow is installed w/ pip
`sudo docker exec -it langflow-backend sh -c "cd /langflow && python3 -m venv env && . env/bin/activate && pip3 install langflow"`


then start the backend with the following command
`sudo docker exec -it langflow-backend sh -c ". env/bin/activate && langflow"`

then hit the domain `langflow.dev.x.com` with your browser

@ogabrielluiz  I'll make a PR for `langflow/backend/langflow_backend/__main__.py` if you're interested.
